-- 회원등록 테이블
CREATE TABLE CAF_ACCOUNT (
    ID          VARCHAR2(20)
    ,PW         VARCHAR2(20)
    ,NAME       VARCHAR2(20)
    ,NICKNAME   VARCHAR2(20)
    ,EMAIL      VARCHAR2(50)    PRIMARY KEY
);

-- 게시글 테이블
CREATE TABLE CAF_POST (
    NUM         NUMBER(5)
    ,TITLE      VARCHAR2(20)
    ,WRITER     VARCHAR2(20)
    ,POST_DATE  DATE
    ,CONTENT    VARCHAR2(20)
    ,PICTURE    VARCHAR2(20)
    ,CAFFEINE NUMBER(20)
    ,EMAIL      VARCHAR2(50) 
    ,CONSTRAINT POST_EMAIL_FK FOREIGN KEY( EMAIL ) REFERENCES CAF_ACCOUNT( EMAIL )
);

-- 게시글 넘버 시퀀스
CREATE SEQUENCE SEQ_POST ;
select SEQ_POST.NEXTVAL from dual;

-- 개인 카페인 섭량 테이블
CREATE TABLE CAF_INTAKE (
    EMAIL       VARCHAR2(50)
    ,AMOUNT     NUMBER(20)
    ,FOREIGN KEY ( EMAIL ) REFERENCES CAF_ACCOUNT( EMAIL )
    );

-- 테이블 확인
SELECT  *   FROM    CAF_ACCOUNT;
SELECT  *   FROM    CAF_POST;
SELECT  *   FROM    CAF_INTAKE;

-- sql등록 테스트
INSERT INTO CAF_ACCOUNT VALUES ('hanji', '0403', 'Hanjiyeon', 'HanjiHanji', 'hanji0403@naver.com');

COMMIT;

--DROP 부분
--DROP TABLE CAF_ACCOUNT;
---DROP TABLE CAF_POST;
--DROP TABLE CAF_INTAKE;
--DROP SEQUENCE SEQ_POST;
