CREATE TABLE CAF_ACCOUNT (
    ID          VARCHAR2(20)
    ,PW         VARCHAR2(20)
    ,NAME       VARCHAR2(20)
    ,NICKNAME   VARCHAR2(20)
    ,EMAIL      VARCHAR2(50)    PRIMARY KEY
);


CREATE TABLE CAF_POST (
    NUM         NUMBER(5)
    ,TITLE      VARCHAR2(20)
    ,WRITER     VARCHAR2(20)
    ,POST_DATE  DATE
    ,CONTENT    VARCHAR2(20)
    ,PICTURE    VARCHAR2(20)
    ,CAFFEINE NUMBER(20)
    ,EMAIL      VARCHAR2(50) 
    ,CONSTRAINT POST_EMAIL_FK FOREIGN KEY( EMAIL ) REFERENCES CAF_ACCOUNT( EMAIL )
);

CREATE SEQUENCE SEQ_POST ;


select SEQ_POST.NEXTVAL from dual;
CREATE TABLE CAF_INTAKE (
    EMAIL       VARCHAR2(50)
    ,AMOUNT     NUMBER(20)
    ,FOREIGN KEY ( EMAIL ) REFERENCES CAF_ACCOUNT( EMAIL )
    );

SELECT  *
FROM    CAF_ACCOUNT;


INSERT INTO CAF_ACCOUNT
VALUES ('hanji', '0403', 'HanjiHanji', 'HanjiHanji', 'hanji0403@naver.com');

COMMIT;


DROP TABLE CAF_ACCOUNT;
DROP TABLE CAF_POST;
DROP TABLE CAF_INTAKE;
DROP SEQUENCE SEQ_POST;
